language: node_js

node_js:
  - "node"
  - "lts/*"
  - "6"
  - "7"
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - ls -lah
  - npm install

script:
  - npm test

notifications:
  email: false
