version: '2'
services:

  node:
    image: node:boron-alpine
    container_name: node
    hostname: node
    volumes:
      - ".:/app"
    working_dir: /app
    command: [sh, -c, npm install --no-bin-links]
